### ISSUE TITLE
Fedora 27

### ISSUE THREAD

**Issue by toanju** [carlwgeorge/ripgrep-rpm#1]
Would you mind enabling builds in F27?
Thanks a lot!

**Comment by carlwgeorge** [comment]
It's enabled now.  Looks like I forget to check the box for "Follow Fedora branching", which I believe will handle this automatically in the future.

The F27 build is queued up and should finish soon.

**Comment by wpoely86** [comment]
I think something went wrong? The only F27 package I can see is 4 months old. There are some fresh ones for F28.

**Comment by carlwgeorge** [comment]
On a test F27 system I can add the repo and install the package successfully.  [Here is the build](https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/build/662773/).    You may be confused because the version in that build says `0.7.1-1.fc28`, but that is just the version-release string from the source RPM.  At the bottom of the page you can see that it was built for the `fedora-27-x86_64` chroot.
